CREATE TABLE t_s_anime_filtered (
    anime_id integer,
    name VARCHAR(255),
    score FLOAT,
    genres TEXT,
    english_name VARCHAR(255),
    japanese_name VARCHAR(255),
    synopsis TEXT,
    type VARCHAR(50),
    episodes VARCHAR(50),
    aired VARCHAR(255),
    premiered VARCHAR(100),
    producers TEXT,
    licensors TEXT,
    studios TEXT,
    source VARCHAR(100),
    duration VARCHAR(100),
    rating VARCHAR(100),
    ranked FLOAT,
    popularity integer,
    members integer,
    favorites integer,
    watching integer,
    completed integer,
    on_hold integer,
    dropped integer
)